Fixing readme template and preview for reports
observatorium/loki-benchmarks pull request #50
Opened 2021-06-28 22:26 UTC by Red-GV

This makes each configuration into a directory and copies the template into them. For that scenario (write or read), those graphs will be displayed. However, the other one will not be displayed.

2021-07-12 05:05 UTC, periklis requested changes
The report dir should provide a single report for all scenarios or at least a table of contents linking the subfolder reports.

2021-07-12 19:08 UTC, Red-GV commented
Went in favor of having a readme table of contents for linking within the various subfolders. The dynamic part of the multi-configurations is more difficult to converge into one report.

2021-07-13 11:53 UTC, periklis commented on benchmarks/benchmarks_suite_test.go
> +
Indentation broken here?

2021-07-13 13:19 UTC, periklis approved these changes

2021-07-13 13:20 UTC, periklis commented
@Red-GV Could you provide also a fix for CircleCI archiving the reports:
```
Unable to save test results from /home/circleci/loki-benchmarks/reports
Error path is not valid "/home/circleci/loki-benchmarks/reports": error accessing path "/home/circleci/loki-benchmarks/reports/2021-07-13-13-02-33/Read-aggregate-203-queries-per-second": open /home/circleci/loki-benchmarks/reports/2021-07-13-13-02-33/Read-aggregate-203-queries-per-second: permission denied
Found no test results, skipping
```

2021-07-14 04:28 UTC, merged