Blog file was added
observatorium/loki-benchmarks pull request #62
Opened 2022-01-06 16:46 UTC by jacobsakran

Report for Benchmark was added

2022-01-10 07:41 UTC, eranra commented
I am looking at the graphs .... sometimes 4 ingesters are blue and sometimes 2 ingesters are blue ... can you change the colors so that the graphs are consistent

2022-01-10 07:43 UTC, eranra commented on blog/report.md
> +We want to give the user the opportunity to know the minimum size of OCP cluster that can stand for his daily logs written and read from Loki. Our goal is to create a table that specifies for each "T
s/minimum size of OCP cluster/recommended LokiStack configuration

explain --> S/XXX/YYY stands for replacing XXX with YYY

2022-01-10 07:44 UTC, eranra commented on blog/report.md
> +We want to give the user the opportunity to know the minimum size of OCP cluster that can stand for his daily logs written and read from Loki. Our goal is to create a table that specifies for each "T
s/OCP/OpenShift

2022-01-10 07:44 UTC, eranra commented on blog/report.md
> +	baseDomain: devcluster.openshift.com
drop `baseDomain` and `apiVersion` this is not needed

2022-01-10 07:44 UTC, eranra commented on blog/report.md
> +We ran that on OpenShift running on AWS clusters with configuration:
s/that/the benchmark

2022-01-10 07:45 UTC, eranra commented on blog/report.md
> +Running with 64 vCPUs and 256 Memory (GiB)
Add: In this configuration each node has

2022-01-10 07:47 UTC, eranra commented on blog/report.md
> +The benchmark tool helps us observe the data (such as CPU, Memory, etc...) of Loki while sending a different amount of logs each test, the logs are sent by a logger that is deployed when the benchmar
s/helps us observe the data/records operational metrics
s/each test,/in each test.

2022-01-10 07:47 UTC, eranra commented on blog/report.md
> +We have been observing mainly the CPU (in MiliCore) and Memory (in GB) as a function of the GiPD (Log load in GB per Day) to see how they change, we ran the benchmark test with different values of Gi
s/, we/. We

2022-01-10 07:49 UTC, eranra commented on blog/report.md
> +
@jacobsakran this looks very good to me. I added comments above for you to fix 

@Red-GV can you review?

2022-01-10 07:53 UTC, eranra commented on blog/report.md
> +
@jacobsakran I am missing two more sections here ... I think we need:

A section called "conclusions" with:
1. From the results we can learn that .... 
2. The information shows clearly that, and the information is not clear on ... 
etc. 

Also, missing is a "TODO/Next" section that talks about what was done and what is still missing. For example, read tests that we did not do at all ... and for example write tests with different values or different scale of different LokiStack components

2022-01-10 07:53 UTC, eranra commented on blog/report.md
> +Getting the GiPD:
s/Getting/Observing (or monitoring)

2022-01-10 07:55 UTC, eranra reviewed
Looks very good @jacobsakran thanks for pulling that together ... please work on the comments and we will work to try and merge this in.

Also, I am not sure that this needs to go into **blog** folder.In any event please add a link to the README to  link into this blog

2022-01-10 13:24 UTC, eranra reviewed
Also, If you can squash those15 commits into a single one

2022-01-10 14:57 UTC, Red-GV requested changes
@eranra @jacobsakran I don't think that the repository is the right medium for this report. This does not add any capabilities nor information for operating the tool.

2022-01-10 15:02 UTC, eranra commented
Hi @Red-GV  ... I would not mind putting that anywhere else (ideas??)  but I think that having a report (I would not call that blog but report) with results showing the value of the benchmark tool and what it can do for specific environments like OpenShift as part of the repo makes a lot of sense, why not??

2022-01-10 15:04 UTC, eranra commented
@Red-GV in any event, if you can review the text + graphs so we can get this ready here or somewhere else

2022-01-10 15:17 UTC, Red-GV commented
@eranra I would think that a better place for reports showing potential performance would be better on websites (like Medium). 

Keeping them in a repository is not very beneficial because this report is something very "specific". For instance, the justification for merging in this would be the same as letting in any report with some statistics for any type of configurations of Loki. That can be potentially bloating.

Mainly, the the repository is for operating the tool. Not for keeping track of the reports or compilations of them.

2022-01-10 15:40 UTC, eranra commented
@Red-GV Sure ... we can do that ... so let's use this PR to agree on text and content and once we are OK with that @jacobsakran  will be able to upload to `medium`

2022-01-16 12:50 UTC, eranra commented on blog/report.md
> +
@jacobsakran can you add another section with TODO/Next that will talk about what is still missing in this evaluation

2022-01-16 12:53 UTC, eranra commented
@jacobsakran one comment that I missed (probably) is that the colors of the graphs are misleading. Sometimes blue is 2 ingesters and sometimes it is brown. Can you fix it so that the same color will represent the same ingesters count

2022-01-16 13:02 UTC, eranra commented
Adding a conclusion section is good. Something is wrong with the indent of the points. When I look on 1. and 2. the text under those points is shown strange.

Also, with regards to the text itself ... if you can talk about the entire spectrum and not on specific points in the graph. For example, say something similar to "we can see that when stressing Loki with log writes up to a level of 2000 GB of data per day, it is clear that with a configuration of 2 ingesters Loki handles the load with a reasonable amount of resources (1 core and 100GB of memory). We also see that load that is above that level is causing the 2 ingesters to consume a lot more memory and CPU, this is a good point to suggest to move into 4 ingesters."

2022-05-31 12:28 UTC, Red-GV commented
Closing PR. As stated, this repository is not meant to act as an archive for generated reports.

2022-05-31 12:28 UTC, closed without merging